# Generated by Django 3.2.25 on 2024-08-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='sobrenome',
            field=models.CharField(default='Desconhecido', max_length=255),
        ),
        migrations.AddField(
            model_name='professor',
            name='sobrenome',
            field=models.CharField(default='Desconhecido', max_length=255),
        ),
    ]
